name: Fetch Weather Data

on:
  schedule:
    - cron: "0 8 * * *" # Exécuter tous les jours à 8h00
  workflow_dispatch: # Permet de déclencher manuellement

jobs:
  fetch-weather-data:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests

      # Exécuter le script Python
      - name: Run Weather Script
        env:
          API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # API Key depuis les secrets GitHub
        run: python script.py
